name: Unittest

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  test:
    name: run python unittests
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: ["3.8", "3.9", "3.10"]
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-versions }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-versions }}
          architecture: 'x64'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Set up Virtual environment
        run: |
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install --upgrade -r requirements.txt
      - name: Unittest
        run:
          python -m unittest discover tests/
